### ISSUE TITLE
requirements and rmsprop

### ISSUE THREAD

**Issue by schuhegger** [Gabsha/ssbr#1]
Hi, 
I think in the requirements file following packages are missing: 
keras
tensorflow 
h5py

Furthermore, I got an error by importing rmsprop. 
Instead of: 
from keras.optimizers import rmsprop
it should be: 
RMSprop instead of rmsprop

**Comment by Gabsha** [comment]
Hi,
Thanks for pointing this out! I left this repo somewhat unfinished...
For now I updated the missing deps and fixed the import issues.
Cheers!
